[[plugins]]
repo = 'Shougo/dein.vim'

# ============================================================
# Utility Tool
# ============================================================
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

# [[plugins]]
# repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'ryochack/BlockDiff'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tyru/operator-camelize.vim'

# [[plugins]]
# repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'lilydjwg/colorizer.git'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree.git'

[[plugins]]
repo = 'Shougo/vinarise'

# ============================================================
# Major Syntax
# ============================================================
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-ltsv'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'vim-scripts/vim-scala'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'https://github.com/isRuslan/vim-es6.git'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = "aklt/plantuml-syntax"

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'vim-scripts/brainfuck-syntax.git'

[[plugins]]
repo = 'vim-scripts/nginx.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

# ============================================================
# ColorScheme
# ============================================================
[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/twilight'

# [[plugins]]
# repo = 'Rip-Rip/clang_complete'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'nsf/gocode'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'dgryski/vim-godef'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'rhysd/vim-crystal'

# for vim
# [[plugins]]
# repo = 'Shougo/neocomplete'
# 
# [[plugins]]
# repo = 'Shougo/neosnippet'


# [[plugins]]
# repo = 'Shougo/neosnippet-snippets' 
# [[plugins]]
# repo = 'ujihisa/neco-ghc'
#
# [[plugins]]
# repo = 'Rip-Rip/clang_complete'
#
# [[plugins]]
# repo = 'h1mesuke/unite-outline'
#
# [[plugins]]
# repo = 'ujihisa/unite-colorscheme'
#
# [[plugins]]
# repo = 'glidenote/memolist.vim'
#
# [[plugins]]
# repo = 'vim-scripts/matchit.zip'
#
# [[plugins]]
# repo = 'ruby-matchit'
#
# [[plugins]]
# repo = 'ujihisa/neco-look.git'
#
# [[plugins]]
# repo = 'thinca/vim-localrc'
#
# [[plugins]]
# repo = 'vim-perl/vim-perl'
#
# [[plugins]]
# repo = 'c9s/perlomni.vim'
#
# [[plugins]]
# repo = "osyo-manga/vim-over"
#
# [[plugins]]
# repo = 'thinca/vim-ref'
#
# [[plugins]]
# repo = 'mattn/perlvalidate-vim.git'
#
# [[plugins]]
# repo = 'elzr/vim-json'
#
# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'
#
